name: Pull Request Check

on: pull_request

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'
      - name: Run unit test
        run: ./gradlew testDebugUnitTest
#      - name: Publish Test Report
#        if: cancelled() != true
#        uses: mikepenz/action-junit-report@v2
#        with:
#          report_paths: '**/build/test-results/*/TEST-*.xml'
#          fail_on_failure: false
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: cancelled() != true
        with:
          name: JUnit Tests
          path: '**/build/test-results/*/TEST-*.xml'
          reporter: java-junit
